### ISSUE TITLE
nil

### ISSUE THREAD

**Issue by woiza** [pkdevel/docker-home#2]
```
2024/11/20 16:29:18 INFO Opening database
2024/11/20 16:29:18 INFO Starting importer interval=1m0s
2024/11/20 16:29:18 DEBUG New DAO with bucket=containers type=**model.Container
2024/11/20 16:29:18 DEBUG New DAO with bucket=endpoints type=**model.Endpoint
2024/11/20 16:29:18 DEBUG Found 18 container(s)
2024/11/20 16:29:18 DEBUG Importing container=docker-home id=edee2af links=[]
2024/11/20 16:29:18 DEBUG Importing container=jellyfin id=1dcea08 links=[]
2024/11/20 16:29:18 DEBUG Importing container=radarr id=6023856 links=[]
2024/11/20 16:29:18 DEBUG Importing container=sonarr id=a445925 links=[]
2024/11/20 16:29:18 DEBUG Importing container=nzbget id=b7641f6 links=[]
2024/11/20 16:29:18 DEBUG Importing container=prowlarr id=c9ebf43 links=[]
2024/11/20 16:29:18 DEBUG Importing container=hass id=6d8041f links=[]
2024/11/20 16:29:18 DEBUG Importing container=mosquitto id=0c3bf4f links=[]
2024/11/20 16:29:18 DEBUG Importing container=hass-daily-restarter id=b13560d links=[]
2024/11/20 16:29:18 DEBUG Importing container=keepalived id=1f13ce0 links=[]
2024/11/20 16:29:18 DEBUG Importing container=adguard id=87ca1f9 links=[]
2024/11/20 16:29:18 DEBUG Importing container=jellyseer id=9208eee links=[]
2024/11/20 16:29:18 DEBUG Importing container=bazarr id=0869345 links=[]
2024/11/20 16:29:18 DEBUG Importing container=hydra id=876c5e9 links=[]
2024/11/20 16:29:18 DEBUG Importing container=recyclarr id=77ef11c links=[]
2024/11/20 16:29:18 DEBUG Importing container=traefik id=8631fba links=[]
2024/11/20 16:29:18 DEBUG Importing container=telegram-bot-radarr id=1725ee1 links=[]
2024/11/20 16:29:18 DEBUG Importing container=telegram-bot-sonarr id=9d5099a links=[]
2024/11/20 16:29:18 INFO Setting up routes
2024/11/20 16:29:18 INFO Starting server
2024/11/20 16:29:27 http: panic serving 192.168.2.5:59071: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xb0
panic({0x355040?, 0x692050?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go.etcd.io/bbolt.(*Bucket).ForEach(0x400002f380?, 0x40001efa50?)
        /go/pkg/mod/go.etcd.io/bbolt@v1.3.10/bucket.go:392 +0x18
github.com/pkdevel/docker-home/internal/pkg/persistence.(*DAO[...]).Find(0x462200, {0x0, 0x0})
        /app/internal/pkg/persistence/dao.go:31 +0xd8
github.com/pkdevel/docker-home/internal/pkg/model.(*Endpoints).Find(...)
        /app/internal/pkg/model/endpoint.go:19
github.com/pkdevel/docker-home/internal/pkg/http.SetupAndServe.func1({0x45f858, 0x40003a2ee0}, 0x40002e4d80)
        /app/internal/pkg/http/router.go:27 +0x68
net/http.HandlerFunc.ServeHTTP(0x6a54e0?, {0x45f858?, 0x40003a2ee0?}, 0x259468?)
        /usr/local/go/src/net/http/server.go:2171 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x45f858, 0x40003a2ee0}, 0x40002e4d80)
        /usr/local/go/src/net/http/server.go:2688 +0x1a4
net/http.serverHandler.ServeHTTP({0x40000c2030?}, {0x45f858?, 0x40003a2ee0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0xbc
net/http.(*conn).serve(0x40003a53b0, {0x460468, 0x400039b230})
        /usr/local/go/src/net/http/server.go:2044 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x3f0
2024/11/20 16:29:27 http: panic serving 192.168.2.5:59075: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xb0
panic({0x355040?, 0x692050?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go.etcd.io/bbolt.(*Bucket).ForEach(0x400002f380?, 0x40001efa50?)
        /go/pkg/mod/go.etcd.io/bbolt@v1.3.10/bucket.go:392 +0x18
github.com/pkdevel/docker-home/internal/pkg/persistence.(*DAO[...]).Find(0x462200, {0x0, 0x0})
        /app/internal/pkg/persistence/dao.go:31 +0xd8
github.com/pkdevel/docker-home/internal/pkg/model.(*Endpoints).Find(...)
        /app/internal/pkg/model/endpoint.go:19
github.com/pkdevel/docker-home/internal/pkg/http.SetupAndServe.func1({0x45f858, 0x40003a30a0}, 0x40002e4ea0)
        /app/internal/pkg/http/router.go:27 +0x68
net/http.HandlerFunc.ServeHTTP(0x6a54e0?, {0x45f858?, 0x40003a30a0?}, 0x259468?)
        /usr/local/go/src/net/http/server.go:2171 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x45f858, 0x40003a30a0}, 0x40002e4ea0)
        /usr/local/go/src/net/http/server.go:2688 +0x1a4
net/http.serverHandler.ServeHTTP({0x400039b500?}, {0x45f858?, 0x40003a30a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0xbc
net/http.(*conn).serve(0x40003a55f0, {0x460468, 0x400039b230})
        /usr/local/go/src/net/http/server.go:2044 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x3f0
2024/11/20 16:29:27 http: panic serving 192.168.2.5:59072: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xb0
panic({0x355040?, 0x692050?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go.etcd.io/bbolt.(*Bucket).ForEach(0x400002f380?, 0x40001efa50?)
        /go/pkg/mod/go.etcd.io/bbolt@v1.3.10/bucket.go:392 +0x18
github.com/pkdevel/docker-home/internal/pkg/persistence.(*DAO[...]).Find(0x462200, {0x0, 0x0})
        /app/internal/pkg/persistence/dao.go:31 +0xd8
github.com/pkdevel/docker-home/internal/pkg/model.(*Endpoints).Find(...)
        /app/internal/pkg/model/endpoint.go:19
github.com/pkdevel/docker-home/internal/pkg/http.SetupAndServe.func1({0x45f858, 0x40003a3260}, 0x40002e4fc0)
        /app/internal/pkg/http/router.go:27 +0x68
net/http.HandlerFunc.ServeHTTP(0x6a54e0?, {0x45f858?, 0x40003a3260?}, 0x259468?)
        /usr/local/go/src/net/http/server.go:2171 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x45f858, 0x40003a3260}, 0x40002e4fc0)
        /usr/local/go/src/net/http/server.go:2688 +0x1a4
net/http.serverHandler.ServeHTTP({0x400039b380?}, {0x45f858?, 0x40003a3260?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0xbc
net/http.(*conn).serve(0x40003a5440, {0x460468, 0x400039b230})
        /usr/local/go/src/net/http/server.go:2044 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x3f0
2024/11/20 16:29:27 http: panic serving 192.168.2.5:59079: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xb0
panic({0x355040?, 0x692050?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go.etcd.io/bbolt.(*Bucket).ForEach(0x400002f380?, 0x40001efa50?)
        /go/pkg/mod/go.etcd.io/bbolt@v1.3.10/bucket.go:392 +0x18
github.com/pkdevel/docker-home/internal/pkg/persistence.(*DAO[...]).Find(0x462200, {0x0, 0x0})
        /app/internal/pkg/persistence/dao.go:31 +0xd8
github.com/pkdevel/docker-home/internal/pkg/model.(*Endpoints).Find(...)
        /app/internal/pkg/model/endpoint.go:19
github.com/pkdevel/docker-home/internal/pkg/http.SetupAndServe.func1({0x45f858, 0x40000d80e0}, 0x40000c8120)
        /app/internal/pkg/http/router.go:27 +0x68
net/http.HandlerFunc.ServeHTTP(0x6a54e0?, {0x45f858?, 0x40000d80e0?}, 0x259468?)
        /usr/local/go/src/net/http/server.go:2171 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x45f858, 0x40000d80e0}, 0x40000c8120)
        /usr/local/go/src/net/http/server.go:2688 +0x1a4
net/http.serverHandler.ServeHTTP({0x40000c22a0?}, {0x45f858?, 0x40000d80e0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0xbc
net/http.(*conn).serve(0x40003a5950, {0x460468, 0x400039b230})
        /usr/local/go/src/net/http/server.go:2044 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x3f0
```

**Comment by pkdevel** [comment]
should be fixed
